export const bgImageforSignupPage: string =
  "https://assets.nflxext.com/ffe/siteui/vlv3/5e48e7b6-350d-48d9-96d6-de8ca173c89f/0383c770-c8a3-4ebc-9292-314180618645/PS-en-20221219-popsignuptwoweeks-perspective_alpha_website_large.jpg";

export const moviesToNotShow = [
  "The Woman King",
  "Black Panther: Wakanda Forever",
  "The Independent",
  "R.I.P.D. 2: Rise of the Damned",
  "The Big 4",
  "Disenchanted",
  "The Guardians of the Galaxy Holiday Special",
  "Thor: Love and Thunder",
  "Glass Onion: A Knives Out Mystery",
  "Bullet Train",
  "Monstrous",
  "Maneater",
  "The Invitation",
  "Bones and All",
  "MexZombies",
  "Orphan: First Kill",
  "In the Forest",
  "Margaux",
  "Frank and Penelope",
  "X",
  "The Friendship Game",
  "Abandoned",
  "Prey for the Devil",
  "Smile",
  "Lyle, Lyle, Crocodile",
  "Piggy",
  "Avatar",
  "My Name Is Vendetta",
];
